pipeline {

    agent none

    stages {

        stage('Build on Kubernetes Agent') {

            agent {
                kubernetes {
                    yamlFile 'food-delivery-3-tier-source-code/K8S/pod.yaml'
                }
            }

            stages {

                stage('Checkout') {
                    steps {
                        checkout scm
                    }
                }

                stage('Check Agent') {
                    steps {
                        container('node') {
                            sh '''
                                echo "===== Kubernetes Jenkins Agent ====="
                                hostname
                                node --version
                                npm --version
                                whoami
                            '''
                        }
                    }
                }

                stage('Backend Build') {
                    steps {
                        container('node') {

                            dir('food-delivery-3-tier-source-code/backend') {

                                sh '''
                                    npm install

                                    echo "Backend dependencies installed successfully"
                                '''
                            }
                        }
                    }
                }


                stage('Frontend Build') {
                    steps {
                        container('node') {

                            dir('food-delivery-3-tier-source-code/frontend') {

                                sh '''
                                    npm install

                                    npm run build

                                    echo "Frontend build completed successfully"
                                '''
                            }
                        }
                    }
                }


                stage('Check Workspace') {
                    steps {
                        container('node') {

                            sh '''
                                echo "===== Workspace ====="

                                pwd

                                ls -la

                                find . -name Dockerfile -print
                            '''
                        }
                    }
                }

            }
        }
    }


    post {

        success {
            echo 'Food Delivery CI Pipeline completed successfully!'
        }

        failure {
            echo 'Food Delivery CI Pipeline failed!'
        }
    }
}
