pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

stage('Backend Build') {
    steps {
        dir('food-delivery-3-tier-source-code/backend') {
            sh '''
                npm install
                echo "Backend dependencies installed successful"
            '''
        }
    }
}

stage('Frontend Build') {
    steps {
        dir('food-delivery-3-tier-source-code/frontend') {
            sh '''
                npm install
                npm run build
                    '''
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh '''
                    docker build -t food-delivery-backend ./backend
                    docker build -t food-delivery-frontend ./frontend
                '''
            }
        }

        stage('Docker Images') {
            steps {
                sh '''
                    docker images | grep food-delivery
                '''
            }
        }
    }

    post {
        success {
            echo 'Food Delivery CI Pipeline completed successfully!'
        }

        failure {
            echo 'Food Delivery CI Pipeline failed!'
        }
    }
}
